
import React from 'react';
import { ProfileData } from '../types';

interface ProfileDisplayProps {
  data: ProfileData;
  onReset: () => void;
}

const ProfileDisplay: React.FC<ProfileDisplayProps> = ({ data, onReset }) => {
  const { header, about, experience } = data;

  // Function to generate the clean, semantic, standalone HTML version
  const getStandaloneHTML = () => {
    let experienceHTML = '';
    if (experience && experience.length > 0) {
      experienceHTML = `
    <section id="experience">
      <h2>Experience</h2>
      ${experience.map(exp => `
      <article>
        <h3>${exp.title}</h3>
        <p><strong>${exp.company}</strong> | ${exp.dates}</p>
        <p>${exp.description}</p>
      </article>`).join('')}
    </section>`;
    }

    let aboutHTML = '';
    if (about) {
      aboutHTML = `
    <section id="about">
      <h2>About</h2>
      <p>${about}</p>
    </section>`;
    }

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${header.name} - Portfolio</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
      background-color: #fff;
    }
    header {
      margin-top: 60px;
      margin-bottom: 60px;
      border-bottom: 2px solid #eee;
      padding-bottom: 20px;
    }
    h1 {
      margin: 0;
      font-size: 2.5em;
      color: #000;
    }
    h2 {
      margin-top: 40px;
      font-size: 1.5em;
      border-bottom: 1px solid #eee;
      padding-bottom: 10px;
    }
    h3 {
      margin-bottom: 5px;
      font-size: 1.25em;
    }
    p {
      margin: 10px 0;
    }
    article {
      margin-bottom: 40px;
    }
    footer {
      margin-top: 80px;
      margin-bottom: 40px;
      border-top: 1px solid #eee;
      padding-top: 20px;
      font-size: 0.85em;
      color: #777;
    }
    @media (max-width: 600px) {
      body { margin: 20px auto; }
      h1 { font-size: 2em; }
    }
  </style>
</head>
<body>
  <header>
    <h1>${header.name}</h1>
    <p>${header.headline}</p>
  </header>

  <main>
    ${aboutHTML}
    ${experienceHTML}
  </main>

  <footer>
    <p>Portfolio generated by LI.Extract Pro - ${new Date().getFullYear()}</p>
  </footer>
</body>
</html>`;
  };

  const downloadHTML = () => {
    const html = getStandaloneHTML();
    const element = document.createElement("a");
    const file = new Blob([html], {type: 'text/html'});
    element.href = URL.createObjectURL(file);
    element.download = "portfolio.html";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen bg-white">
      {/* App Toolbar (Not part of the generated website) */}
      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur-sm border-b border-neutral-100 px-6 py-4 flex justify-between items-center no-print">
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-green-500"></div>
          <span className="text-[10px] font-black uppercase tracking-[0.2em] text-neutral-400">Website Ready</span>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={downloadHTML}
            className="text-[10px] bg-neutral-900 hover:bg-black text-white font-black uppercase tracking-widest py-2.5 px-6 rounded-lg shadow-lg transition-all"
          >
            Download HTML File
          </button>
          <button 
            onClick={onReset}
            className="text-[10px] bg-neutral-100 hover:bg-neutral-200 text-neutral-600 font-black uppercase tracking-widest py-2.5 px-6 rounded-lg transition-all"
          >
            New Scan
          </button>
        </div>
      </nav>

      {/* The Website Content - Strictly following "Article-like reading flow" */}
      <div className="max-w-3xl mx-auto px-6 py-20 animate-in fade-in duration-1000">
        
        <header className="mb-20 border-b-2 border-neutral-50 pb-12 text-center md:text-left">
          <h1 className="text-5xl md:text-6xl font-serif font-black tracking-tight text-neutral-950 mb-4">
            {header.name || 'Anonymous'}
          </h1>
          <p className="text-xl md:text-2xl text-neutral-500 font-medium leading-relaxed max-w-2xl">
            {header.headline}
          </p>
        </header>

        <main className="space-y-24">
          
          {/* About Section */}
          {about && (
            <section className="prose prose-neutral max-w-none">
              <h2 className="text-xs font-black uppercase tracking-[0.3em] text-neutral-400 mb-8 flex items-center gap-4">
                <span>About</span>
                <div className="h-px flex-1 bg-neutral-100"></div>
              </h2>
              <div className="text-xl text-neutral-700 leading-relaxed font-serif whitespace-pre-wrap">
                {about}
              </div>
            </section>
          )}

          {/* Experience Section */}
          {experience && experience.length > 0 && (
            <section className="prose prose-neutral max-w-none">
              <h2 className="text-xs font-black uppercase tracking-[0.3em] text-neutral-400 mb-12 flex items-center gap-4">
                <span>Experience</span>
                <div className="h-px flex-1 bg-neutral-100"></div>
              </h2>
              <div className="space-y-16">
                {experience.map((exp, idx) => (
                  <article key={idx} className="group">
                    <header className="mb-4">
                      <h3 className="text-2xl font-black text-neutral-950 mb-1 leading-tight group-hover:text-neutral-700 transition-colors">
                        {exp.title}
                      </h3>
                      <p className="text-sm font-black uppercase tracking-widest text-neutral-400 flex flex-wrap items-center gap-2">
                        <span>{exp.company}</span>
                        <span className="text-neutral-200">•</span>
                        <span>{exp.dates}</span>
                      </p>
                    </header>
                    <div className="text-neutral-600 leading-relaxed whitespace-pre-wrap font-medium">
                      {exp.description}
                    </div>
                  </article>
                ))}
              </div>
            </section>
          )}

        </main>

        <footer className="mt-32 pt-12 border-t border-neutral-100 text-center">
          <p className="text-[10px] font-black uppercase tracking-[0.3em] text-neutral-300">
            &copy; {new Date().getFullYear()} {header.name}
          </p>
        </footer>
      </div>
    </div>
  );
};

export default ProfileDisplay;
